name = "TriangleMesh"
uuid = "e5719326-7e34-5a7d-b19a-3e86f2e9acf7"
authors = ["Konrad Simon <konrad.simon@uni-hamburg.de>"]
version = "v1.1.1"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
julia = "^1.0.5"
BinDeps = "^1"
ProgressMeter = "^1"
